apiVersion: v1
kind: Service
metadata:
  name: ml-serving-api
  labels:
    app: ml-serving-api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: ml-serving-api
